namespace R6DataAccess.Models
{
    public interface IEquipmentStatistic
    {
        int GadgetpveChosen108F856206Infinite { get; set; }
        int GadgetpveChosen143D8A7F46Infinite { get; set; }
        int GadgetpveChosen1F7D4C789AInfinite { get; set; }
        int GadgetpveChosen1FC75DB98Infinite { get; set; }
        int GadgetpveChosen2305F2E8CFInfinite { get; set; }
        int GadgetpveChosen232803C7B3Infinite { get; set; }
        int GadgetpveChosen24F948E748Infinite { get; set; }
        int GadgetpveChosen24F9498268Infinite { get; set; }
        int GadgetpveChosen24F9498269Infinite { get; set; }
        int GadgetpveChosen251D51968CInfinite { get; set; }
        int GadgetpveChosen2A4CEB729CInfinite { get; set; }
        int GadgetpveChosen2C06F6BBC5Infinite { get; set; }
        int GadgetpveChosen37E0A74DD2Infinite { get; set; }
        int GadgetpveChosen37E0A74DD4Infinite { get; set; }
        int GadgetpveChosen38B9A2CB16Infinite { get; set; }
        int GadgetpveChosen38FA6AE7CEInfinite { get; set; }
        int GadgetpveChosen38FA6B0D49Infinite { get; set; }
        int GadgetpveChosen395EBC0A4EInfinite { get; set; }
        int GadgetpveChosen3A39663A6FInfinite { get; set; }
        int GadgetpveChosen731005332Infinite { get; set; }
        int GadgetpveChosen883555882Infinite { get; set; }
        int GadgetpveChosen96ED81DE6Infinite { get; set; }
        int GadgetpveChosen9B2CAEBAInfinite { get; set; }
        int GadgetpveChosenADC64DD49Infinite { get; set; }
        int GadgetpveChosenB793109FInfinite { get; set; }
        int GadgetpveChosenB79310A0Infinite { get; set; }
        int GadgetpveChosenB79310A1Infinite { get; set; }
        int GadgetpveChosenB79310A3Infinite { get; set; }
        int GadgetpveChosenB79310A5Infinite { get; set; }
        int GadgetpveChosenB79310A7Infinite { get; set; }
        int GadgetpveChosenB79310AAInfinite { get; set; }
        int GadgetpveChosenB79310ABInfinite { get; set; }
        int GadgetpveChosenB79310ACInfinite { get; set; }
        int GadgetpveChosenB79310ADInfinite { get; set; }
        int GadgetpveChosenB79310AFInfinite { get; set; }
        int GadgetpveChosenB79310B4Infinite { get; set; }
        int GadgetpveChosenB79310B5Infinite { get; set; }
        int GadgetpveChosenB79310B7Infinite { get; set; }
        int GadgetpveChosenB79310B9Infinite { get; set; }
        int GadgetpveChosenB79310BAInfinite { get; set; }
        int GadgetpveChosenB79310BBInfinite { get; set; }
        int GadgetpveChosenB79310BCInfinite { get; set; }
        int GadgetpveChosenB79310BDInfinite { get; set; }
        int GadgetpveChosenE3707E47FInfinite { get; set; }
        int GadgetpveChosenFF436317BInfinite { get; set; }
        int GadgetpveKills36232BA67DInfinite { get; set; }
        int GadgetpveKills38B9A14617Infinite { get; set; }
        int GadgetpveKills38B9A2CB16Infinite { get; set; }
        int GadgetpveKillsA44721360Infinite { get; set; }
        int GadgetpveKillsB79310CBInfinite { get; set; }
        int GadgetpvpKills1CBF13F5FBInfinite { get; set; }
        int GadgetpvpKills36232BA67DInfinite { get; set; }
        int GadgetpvpKills38B9A14617Infinite { get; set; }
        int GadgetpvpKills38B9A2CB16Infinite { get; set; }
        int GadgetpvpKills80CA9890CInfinite { get; set; }
        int GadgetpvpKills9A9F55EF9Infinite { get; set; }
        int GadgetpvpKillsA44721360Infinite { get; set; }
        int GadgetpvpKillsB79310CBInfinite { get; set; }
        int WeapontypepveBulletfired1Infinite { get; set; }
        int WeapontypepveBulletfired2Infinite { get; set; }
        int WeapontypepveBulletfired3Infinite { get; set; }
        int WeapontypepveBulletfired4Infinite { get; set; }
        int WeapontypepveBulletfired5Infinite { get; set; }
        int WeapontypepveBulletfired6Infinite { get; set; }
        int WeapontypepveBulletfired7Infinite { get; set; }
        int WeapontypepveBullethit1Infinite { get; set; }
        int WeapontypepveBullethit2Infinite { get; set; }
        int WeapontypepveBullethit3Infinite { get; set; }
        int WeapontypepveBullethit4Infinite { get; set; }
        int WeapontypepveBullethit5Infinite { get; set; }
        int WeapontypepveBullethit6Infinite { get; set; }
        int WeapontypepveBullethit7Infinite { get; set; }
        int WeapontypepveChosen1Infinite { get; set; }
        int WeapontypepveChosen2Infinite { get; set; }
        int WeapontypepveChosen3Infinite { get; set; }
        int WeapontypepveChosen4Infinite { get; set; }
        int WeapontypepveChosen5Infinite { get; set; }
        int WeapontypepveChosen6Infinite { get; set; }
        int WeapontypepveChosen7Infinite { get; set; }
        int WeapontypepveChosen9Infinite { get; set; }
        int WeapontypepveDeath1Infinite { get; set; }
        int WeapontypepveDeath5Infinite { get; set; }
        int WeapontypepveDeath6Infinite { get; set; }
        int WeapontypepveHeadshot1Infinite { get; set; }
        int WeapontypepveHeadshot2Infinite { get; set; }
        int WeapontypepveHeadshot3Infinite { get; set; }
        int WeapontypepveHeadshot4Infinite { get; set; }
        int WeapontypepveHeadshot5Infinite { get; set; }
        int WeapontypepveHeadshot6Infinite { get; set; }
        int WeapontypepveHeadshot7Infinite { get; set; }
        int WeapontypepveKills1Infinite { get; set; }
        int WeapontypepveKills2Infinite { get; set; }
        int WeapontypepveKills3Infinite { get; set; }
        int WeapontypepveKills4Infinite { get; set; }
        int WeapontypepveKills5Infinite { get; set; }
        int WeapontypepveKills6Infinite { get; set; }
        int WeapontypepveKills7Infinite { get; set; }
        int WeapontypepvpBullethit1Infinite { get; set; }
        int WeapontypepvpBullethit2Infinite { get; set; }
        int WeapontypepvpBullethit3Infinite { get; set; }
        int WeapontypepvpBullethit4Infinite { get; set; }
        int WeapontypepvpBullethit5Infinite { get; set; }
        int WeapontypepvpBullethit6Infinite { get; set; }
        int WeapontypepvpBullethit7Infinite { get; set; }
        int WeapontypepvpBullethitBInfinite { get; set; }
        int WeapontypepvpBullethitCInfinite { get; set; }
        int WeapontypepvpChosen1Infinite { get; set; }
        int WeapontypepvpChosen2Infinite { get; set; }
        int WeapontypepvpChosen3Infinite { get; set; }
        int WeapontypepvpChosen4Infinite { get; set; }
        int WeapontypepvpChosen5Infinite { get; set; }
        int WeapontypepvpChosen6Infinite { get; set; }
        int WeapontypepvpChosen7Infinite { get; set; }
        int WeapontypepvpChosen9Infinite { get; set; }
        int WeapontypepvpChosenBInfinite { get; set; }
        int WeapontypepvpDbno1Infinite { get; set; }
        int WeapontypepvpDbno2Infinite { get; set; }
        int WeapontypepvpDbno3Infinite { get; set; }
        int WeapontypepvpDbno4Infinite { get; set; }
        int WeapontypepvpDbno5Infinite { get; set; }
        int WeapontypepvpDbno6Infinite { get; set; }
        int WeapontypepvpDbno7Infinite { get; set; }
        int WeapontypepvpDbnoassists1Infinite { get; set; }
        int WeapontypepvpDbnoassists2Infinite { get; set; }
        int WeapontypepvpDbnoassists3Infinite { get; set; }
        int WeapontypepvpDbnoassists4Infinite { get; set; }
        int WeapontypepvpDbnoassists5Infinite { get; set; }
        int WeapontypepvpDbnoassists6Infinite { get; set; }
        int WeapontypepvpDbnoassists7Infinite { get; set; }
        int WeapontypepvpDbnoassists9Infinite { get; set; }
        int WeapontypepvpDbnoassistsCInfinite { get; set; }
        int WeapontypepvpDbnoBInfinite { get; set; }
        int WeapontypepvpDeath1Infinite { get; set; }
        int WeapontypepvpDeath2Infinite { get; set; }
        int WeapontypepvpDeath3Infinite { get; set; }
        int WeapontypepvpDeath4Infinite { get; set; }
        int WeapontypepvpDeath5Infinite { get; set; }
        int WeapontypepvpDeath6Infinite { get; set; }
        int WeapontypepvpDeath7Infinite { get; set; }
        int WeapontypepvpDeathBInfinite { get; set; }
        int WeapontypepvpHeadshot1Infinite { get; set; }
        int WeapontypepvpHeadshot2Infinite { get; set; }
        int WeapontypepvpHeadshot3Infinite { get; set; }
        int WeapontypepvpHeadshot4Infinite { get; set; }
        int WeapontypepvpHeadshot5Infinite { get; set; }
        int WeapontypepvpHeadshot6Infinite { get; set; }
        int WeapontypepvpHeadshot7Infinite { get; set; }
        int WeapontypepvpHeadshotBInfinite { get; set; }
        int WeapontypepvpKills1Infinite { get; set; }
        int WeapontypepvpKills2Infinite { get; set; }
        int WeapontypepvpKills3Infinite { get; set; }
        int WeapontypepvpKills4Infinite { get; set; }
        int WeapontypepvpKills5Infinite { get; set; }
        int WeapontypepvpKills6Infinite { get; set; }
        int WeapontypepvpKills7Infinite { get; set; }
        int WeapontypepvpKillsBInfinite { get; set; }
    }
}