namespace R6DataAccess.Models
{
    public interface IOperatorStatistic
    {
        int OperatorpveAshBonfirewallbreached32Infinite { get; set; }
        int OperatorpveBuckKill26Infinite { get; set; }
        int OperatorpveCapitaoLethaldartkills28Infinite { get; set; }
        int OperatorpveCastleKevlarbarricadedeployed22Infinite { get; set; }
        int OperatorpveDeath11Infinite { get; set; }
        int OperatorpveDeath13Infinite { get; set; }
        int OperatorpveDeath210Infinite { get; set; }
        int OperatorpveDeath211Infinite { get; set; }
        int OperatorpveDeath213Infinite { get; set; }
        int OperatorpveDeath219Infinite { get; set; }
        int OperatorpveDeath22Infinite { get; set; }
        int OperatorpveDeath24Infinite { get; set; }
        int OperatorpveDeath26Infinite { get; set; }
        int OperatorpveDeath28Infinite { get; set; }
        int OperatorpveDeath29Infinite { get; set; }
        int OperatorpveDeath2BInfinite { get; set; }
        int OperatorpveDeath2FInfinite { get; set; }
        int OperatorpveDeath32Infinite { get; set; }
        int OperatorpveDeath33Infinite { get; set; }
        int OperatorpveDeath34Infinite { get; set; }
        int OperatorpveDeath35Infinite { get; set; }
        int OperatorpveDeath39Infinite { get; set; }
        int OperatorpveDeath3BInfinite { get; set; }
        int OperatorpveDeath3DInfinite { get; set; }
        int OperatorpveDeath41Infinite { get; set; }
        int OperatorpveDeath42Infinite { get; set; }
        int OperatorpveDeath43Infinite { get; set; }
        int OperatorpveDeath4EInfinite { get; set; }
        int OperatorpveDeath51Infinite { get; set; }
        int OperatorpveDeath52Infinite { get; set; }
        int OperatorpveDeath53Infinite { get; set; }
        int OperatorpveDeath55Infinite { get; set; }
        int OperatorpveFrostBeartrapKill36Infinite { get; set; }
        int OperatorpveFuzeClusterchargekill34Infinite { get; set; }
        int OperatorpveGlazSniperkill24Infinite { get; set; }
        int OperatorpveGlazSniperpenetrationkill24Infinite { get; set; }
        int OperatorpveHeadshot11Infinite { get; set; }
        int OperatorpveHeadshot12Infinite { get; set; }
        int OperatorpveHeadshot13Infinite { get; set; }
        int OperatorpveHeadshot210Infinite { get; set; }
        int OperatorpveHeadshot212Infinite { get; set; }
        int OperatorpveHeadshot213Infinite { get; set; }
        int OperatorpveHeadshot218Infinite { get; set; }
        int OperatorpveHeadshot219Infinite { get; set; }
        int OperatorpveHeadshot21Infinite { get; set; }
        int OperatorpveHeadshot22Infinite { get; set; }
        int OperatorpveHeadshot23Infinite { get; set; }
        int OperatorpveHeadshot24Infinite { get; set; }
        int OperatorpveHeadshot25Infinite { get; set; }
        int OperatorpveHeadshot26Infinite { get; set; }
        int OperatorpveHeadshot28Infinite { get; set; }
        int OperatorpveHeadshot29Infinite { get; set; }
        int OperatorpveHeadshot2BInfinite { get; set; }
        int OperatorpveHeadshot2CInfinite { get; set; }
        int OperatorpveHeadshot2FInfinite { get; set; }
        int OperatorpveHeadshot311Infinite { get; set; }
        int OperatorpveHeadshot312Infinite { get; set; }
        int OperatorpveHeadshot32Infinite { get; set; }
        int OperatorpveHeadshot33Infinite { get; set; }
        int OperatorpveHeadshot34Infinite { get; set; }
        int OperatorpveHeadshot35Infinite { get; set; }
        int OperatorpveHeadshot36Infinite { get; set; }
        int OperatorpveHeadshot37Infinite { get; set; }
        int OperatorpveHeadshot39Infinite { get; set; }
        int OperatorpveHeadshot3BInfinite { get; set; }
        int OperatorpveHeadshot3CInfinite { get; set; }
        int OperatorpveHeadshot3DInfinite { get; set; }
        int OperatorpveHeadshot3FInfinite { get; set; }
        int OperatorpveHeadshot417Infinite { get; set; }
        int OperatorpveHeadshot41Infinite { get; set; }
        int OperatorpveHeadshot42Infinite { get; set; }
        int OperatorpveHeadshot43Infinite { get; set; }
        int OperatorpveHeadshot44Infinite { get; set; }
        int OperatorpveHeadshot4EInfinite { get; set; }
        int OperatorpveHeadshot51Infinite { get; set; }
        int OperatorpveHeadshot52Infinite { get; set; }
        int OperatorpveHeadshot53Infinite { get; set; }
        int OperatorpveHeadshot55Infinite { get; set; }
        int OperatorpveHibanaDetonateProjectile29Infinite { get; set; }
        int OperatorpveIqGadgetspotbyef35Infinite { get; set; }
        int OperatorpveKapkanBoobytrapdeployed44Infinite { get; set; }
        int OperatorpveKapkanBoobytrapkill44Infinite { get; set; }
        int OperatorpveKills11Infinite { get; set; }
        int OperatorpveKills12Infinite { get; set; }
        int OperatorpveKills13Infinite { get; set; }
        int OperatorpveKills210Infinite { get; set; }
        int OperatorpveKills211Infinite { get; set; }
        int OperatorpveKills212Infinite { get; set; }
        int OperatorpveKills213Infinite { get; set; }
        int OperatorpveKills218Infinite { get; set; }
        int OperatorpveKills219Infinite { get; set; }
        int OperatorpveKills21Infinite { get; set; }
        int OperatorpveKills22Infinite { get; set; }
        int OperatorpveKills23Infinite { get; set; }
        int OperatorpveKills24Infinite { get; set; }
        int OperatorpveKills25Infinite { get; set; }
        int OperatorpveKills26Infinite { get; set; }
        int OperatorpveKills28Infinite { get; set; }
        int OperatorpveKills29Infinite { get; set; }
        int OperatorpveKills2BInfinite { get; set; }
        int OperatorpveKills2CInfinite { get; set; }
        int OperatorpveKills2FInfinite { get; set; }
        int OperatorpveKills311Infinite { get; set; }
        int OperatorpveKills312Infinite { get; set; }
        int OperatorpveKills32Infinite { get; set; }
        int OperatorpveKills33Infinite { get; set; }
        int OperatorpveKills34Infinite { get; set; }
        int OperatorpveKills35Infinite { get; set; }
        int OperatorpveKills36Infinite { get; set; }
        int OperatorpveKills37Infinite { get; set; }
        int OperatorpveKills39Infinite { get; set; }
        int OperatorpveKills3BInfinite { get; set; }
        int OperatorpveKills3CInfinite { get; set; }
        int OperatorpveKills3DInfinite { get; set; }
        int OperatorpveKills3FInfinite { get; set; }
        int OperatorpveKills417Infinite { get; set; }
        int OperatorpveKills41Infinite { get; set; }
        int OperatorpveKills42Infinite { get; set; }
        int OperatorpveKills43Infinite { get; set; }
        int OperatorpveKills44Infinite { get; set; }
        int OperatorpveKills4EInfinite { get; set; }
        int OperatorpveKills51Infinite { get; set; }
        int OperatorpveKills52Infinite { get; set; }
        int OperatorpveKills53Infinite { get; set; }
        int OperatorpveKills55Infinite { get; set; }
        int OperatorpveMeleekills210Infinite { get; set; }
        int OperatorpveMeleekills211Infinite { get; set; }
        int OperatorpveMeleekills212Infinite { get; set; }
        int OperatorpveMeleekills213Infinite { get; set; }
        int OperatorpveMeleekills219Infinite { get; set; }
        int OperatorpveMeleekills23Infinite { get; set; }
        int OperatorpveMeleekills24Infinite { get; set; }
        int OperatorpveMeleekills26Infinite { get; set; }
        int OperatorpveMeleekills28Infinite { get; set; }
        int OperatorpveMeleekills29Infinite { get; set; }
        int OperatorpveMeleekills2BInfinite { get; set; }
        int OperatorpveMeleekills32Infinite { get; set; }
        int OperatorpveMeleekills34Infinite { get; set; }
        int OperatorpveMeleekills35Infinite { get; set; }
        int OperatorpveMeleekills37Infinite { get; set; }
        int OperatorpveMeleekills39Infinite { get; set; }
        int OperatorpveMeleekills3BInfinite { get; set; }
        int OperatorpveMeleekills3CInfinite { get; set; }
        int OperatorpveMeleekills41Infinite { get; set; }
        int OperatorpveMeleekills43Infinite { get; set; }
        int OperatorpveMeleekills44Infinite { get; set; }
        int OperatorpveMeleekills4EInfinite { get; set; }
        int OperatorpveMeleekills51Infinite { get; set; }
        int OperatorpveMeleekills52Infinite { get; set; }
        int OperatorpveMeleekills53Infinite { get; set; }
        int OperatorpveRookArmorboxdeployed33Infinite { get; set; }
        int OperatorpveRookArmortakenourself33Infinite { get; set; }
        int OperatorpveRookArmortakenteammate33Infinite { get; set; }
        int OperatorpveRoundlost11Infinite { get; set; }
        int OperatorpveRoundlost13Infinite { get; set; }
        int OperatorpveRoundlost213Infinite { get; set; }
        int OperatorpveRoundlost219Infinite { get; set; }
        int OperatorpveRoundlost23Infinite { get; set; }
        int OperatorpveRoundlost24Infinite { get; set; }
        int OperatorpveRoundlost26Infinite { get; set; }
        int OperatorpveRoundlost29Infinite { get; set; }
        int OperatorpveRoundlost2BInfinite { get; set; }
        int OperatorpveRoundlost2FInfinite { get; set; }
        int OperatorpveRoundlost32Infinite { get; set; }
        int OperatorpveRoundlost33Infinite { get; set; }
        int OperatorpveRoundlost35Infinite { get; set; }
        int OperatorpveRoundlost39Infinite { get; set; }
        int OperatorpveRoundlost3DInfinite { get; set; }
        int OperatorpveRoundlost41Infinite { get; set; }
        int OperatorpveRoundlost42Infinite { get; set; }
        int OperatorpveRoundlost43Infinite { get; set; }
        int OperatorpveRoundlost4EInfinite { get; set; }
        int OperatorpveRoundlost51Infinite { get; set; }
        int OperatorpveRoundlost52Infinite { get; set; }
        int OperatorpveRoundlost55Infinite { get; set; }
        int OperatorpveRoundplayed11Infinite { get; set; }
        int OperatorpveRoundplayed12Infinite { get; set; }
        int OperatorpveRoundplayed13Infinite { get; set; }
        int OperatorpveRoundplayed210Infinite { get; set; }
        int OperatorpveRoundplayed211Infinite { get; set; }
        int OperatorpveRoundplayed212Infinite { get; set; }
        int OperatorpveRoundplayed213Infinite { get; set; }
        int OperatorpveRoundplayed218Infinite { get; set; }
        int OperatorpveRoundplayed219Infinite { get; set; }
        int OperatorpveRoundplayed21Infinite { get; set; }
        int OperatorpveRoundplayed22Infinite { get; set; }
        int OperatorpveRoundplayed23Infinite { get; set; }
        int OperatorpveRoundplayed24Infinite { get; set; }
        int OperatorpveRoundplayed25Infinite { get; set; }
        int OperatorpveRoundplayed26Infinite { get; set; }
        int OperatorpveRoundplayed28Infinite { get; set; }
        int OperatorpveRoundplayed29Infinite { get; set; }
        int OperatorpveRoundplayed2BInfinite { get; set; }
        int OperatorpveRoundplayed2CInfinite { get; set; }
        int OperatorpveRoundplayed2FInfinite { get; set; }
        int OperatorpveRoundplayed311Infinite { get; set; }
        int OperatorpveRoundplayed312Infinite { get; set; }
        int OperatorpveRoundplayed32Infinite { get; set; }
        int OperatorpveRoundplayed33Infinite { get; set; }
        int OperatorpveRoundplayed34Infinite { get; set; }
        int OperatorpveRoundplayed35Infinite { get; set; }
        int OperatorpveRoundplayed36Infinite { get; set; }
        int OperatorpveRoundplayed37Infinite { get; set; }
        int OperatorpveRoundplayed39Infinite { get; set; }
        int OperatorpveRoundplayed3BInfinite { get; set; }
        int OperatorpveRoundplayed3CInfinite { get; set; }
        int OperatorpveRoundplayed3DInfinite { get; set; }
        int OperatorpveRoundplayed3FInfinite { get; set; }
        int OperatorpveRoundplayed417Infinite { get; set; }
        int OperatorpveRoundplayed41Infinite { get; set; }
        int OperatorpveRoundplayed42Infinite { get; set; }
        int OperatorpveRoundplayed43Infinite { get; set; }
        int OperatorpveRoundplayed44Infinite { get; set; }
        int OperatorpveRoundplayed4EInfinite { get; set; }
        int OperatorpveRoundplayed51Infinite { get; set; }
        int OperatorpveRoundplayed52Infinite { get; set; }
        int OperatorpveRoundplayed53Infinite { get; set; }
        int OperatorpveRoundplayed55Infinite { get; set; }
        int OperatorpveRoundwon11Infinite { get; set; }
        int OperatorpveRoundwon12Infinite { get; set; }
        int OperatorpveRoundwon13Infinite { get; set; }
        int OperatorpveRoundwon210Infinite { get; set; }
        int OperatorpveRoundwon211Infinite { get; set; }
        int OperatorpveRoundwon212Infinite { get; set; }
        int OperatorpveRoundwon213Infinite { get; set; }
        int OperatorpveRoundwon218Infinite { get; set; }
        int OperatorpveRoundwon219Infinite { get; set; }
        int OperatorpveRoundwon21Infinite { get; set; }
        int OperatorpveRoundwon22Infinite { get; set; }
        int OperatorpveRoundwon23Infinite { get; set; }
        int OperatorpveRoundwon24Infinite { get; set; }
        int OperatorpveRoundwon25Infinite { get; set; }
        int OperatorpveRoundwon26Infinite { get; set; }
        int OperatorpveRoundwon28Infinite { get; set; }
        int OperatorpveRoundwon29Infinite { get; set; }
        int OperatorpveRoundwon2BInfinite { get; set; }
        int OperatorpveRoundwon2CInfinite { get; set; }
        int OperatorpveRoundwon311Infinite { get; set; }
        int OperatorpveRoundwon312Infinite { get; set; }
        int OperatorpveRoundwon32Infinite { get; set; }
        int OperatorpveRoundwon34Infinite { get; set; }
        int OperatorpveRoundwon35Infinite { get; set; }
        int OperatorpveRoundwon36Infinite { get; set; }
        int OperatorpveRoundwon37Infinite { get; set; }
        int OperatorpveRoundwon3BInfinite { get; set; }
        int OperatorpveRoundwon3CInfinite { get; set; }
        int OperatorpveRoundwon3DInfinite { get; set; }
        int OperatorpveRoundwon3FInfinite { get; set; }
        int OperatorpveRoundwon417Infinite { get; set; }
        int OperatorpveRoundwon41Infinite { get; set; }
        int OperatorpveRoundwon43Infinite { get; set; }
        int OperatorpveRoundwon44Infinite { get; set; }
        int OperatorpveRoundwon4EInfinite { get; set; }
        int OperatorpveRoundwon51Infinite { get; set; }
        int OperatorpveRoundwon52Infinite { get; set; }
        int OperatorpveRoundwon53Infinite { get; set; }
        int OperatorpveRoundwon55Infinite { get; set; }
        int OperatorpveSledgeHammerhole41Infinite { get; set; }
        int OperatorpveSledgeHammerkill41Infinite { get; set; }
        int OperatorpveSmokePoisongaskill21Infinite { get; set; }
        int OperatorpveThatcherGadgetdestroywithemp51Infinite { get; set; }
        int OperatorpveThermiteChargedeployed52Infinite { get; set; }
        int OperatorpveThermiteReinforcementbreached52Infinite { get; set; }
        int OperatorpveTimeplayed11Infinite { get; set; }
        int OperatorpveTimeplayed12Infinite { get; set; }
        int OperatorpveTimeplayed13Infinite { get; set; }
        int OperatorpveTimeplayed210Infinite { get; set; }
        int OperatorpveTimeplayed211Infinite { get; set; }
        int OperatorpveTimeplayed212Infinite { get; set; }
        int OperatorpveTimeplayed213Infinite { get; set; }
        int OperatorpveTimeplayed218Infinite { get; set; }
        int OperatorpveTimeplayed219Infinite { get; set; }
        int OperatorpveTimeplayed21Infinite { get; set; }
        int OperatorpveTimeplayed22Infinite { get; set; }
        int OperatorpveTimeplayed23Infinite { get; set; }
        int OperatorpveTimeplayed24Infinite { get; set; }
        int OperatorpveTimeplayed25Infinite { get; set; }
        int OperatorpveTimeplayed26Infinite { get; set; }
        int OperatorpveTimeplayed28Infinite { get; set; }
        int OperatorpveTimeplayed29Infinite { get; set; }
        int OperatorpveTimeplayed2BInfinite { get; set; }
        int OperatorpveTimeplayed2CInfinite { get; set; }
        int OperatorpveTimeplayed2FInfinite { get; set; }
        int OperatorpveTimeplayed311Infinite { get; set; }
        int OperatorpveTimeplayed312Infinite { get; set; }
        int OperatorpveTimeplayed32Infinite { get; set; }
        int OperatorpveTimeplayed33Infinite { get; set; }
        int OperatorpveTimeplayed34Infinite { get; set; }
        int OperatorpveTimeplayed35Infinite { get; set; }
        int OperatorpveTimeplayed36Infinite { get; set; }
        int OperatorpveTimeplayed37Infinite { get; set; }
        int OperatorpveTimeplayed39Infinite { get; set; }
        int OperatorpveTimeplayed3BInfinite { get; set; }
        int OperatorpveTimeplayed3CInfinite { get; set; }
        int OperatorpveTimeplayed3DInfinite { get; set; }
        int OperatorpveTimeplayed3FInfinite { get; set; }
        int OperatorpveTimeplayed417Infinite { get; set; }
        int OperatorpveTimeplayed41Infinite { get; set; }
        int OperatorpveTimeplayed42Infinite { get; set; }
        int OperatorpveTimeplayed43Infinite { get; set; }
        int OperatorpveTimeplayed44Infinite { get; set; }
        int OperatorpveTimeplayed4EInfinite { get; set; }
        int OperatorpveTimeplayed51Infinite { get; set; }
        int OperatorpveTimeplayed52Infinite { get; set; }
        int OperatorpveTimeplayed53Infinite { get; set; }
        int OperatorpveTimeplayed55Infinite { get; set; }
        int OperatorpveTotalxp11Infinite { get; set; }
        int OperatorpveTotalxp12Infinite { get; set; }
        int OperatorpveTotalxp13Infinite { get; set; }
        int OperatorpveTotalxp210Infinite { get; set; }
        int OperatorpveTotalxp211Infinite { get; set; }
        int OperatorpveTotalxp212Infinite { get; set; }
        int OperatorpveTotalxp213Infinite { get; set; }
        int OperatorpveTotalxp218Infinite { get; set; }
        int OperatorpveTotalxp219Infinite { get; set; }
        int OperatorpveTotalxp21Infinite { get; set; }
        int OperatorpveTotalxp22Infinite { get; set; }
        int OperatorpveTotalxp23Infinite { get; set; }
        int OperatorpveTotalxp24Infinite { get; set; }
        int OperatorpveTotalxp25Infinite { get; set; }
        int OperatorpveTotalxp26Infinite { get; set; }
        int OperatorpveTotalxp28Infinite { get; set; }
        int OperatorpveTotalxp29Infinite { get; set; }
        int OperatorpveTotalxp2BInfinite { get; set; }
        int OperatorpveTotalxp2CInfinite { get; set; }
        int OperatorpveTotalxp2FInfinite { get; set; }
        int OperatorpveTotalxp311Infinite { get; set; }
        int OperatorpveTotalxp312Infinite { get; set; }
        int OperatorpveTotalxp32Infinite { get; set; }
        int OperatorpveTotalxp33Infinite { get; set; }
        int OperatorpveTotalxp34Infinite { get; set; }
        int OperatorpveTotalxp35Infinite { get; set; }
        int OperatorpveTotalxp36Infinite { get; set; }
        int OperatorpveTotalxp37Infinite { get; set; }
        int OperatorpveTotalxp39Infinite { get; set; }
        int OperatorpveTotalxp3BInfinite { get; set; }
        int OperatorpveTotalxp3CInfinite { get; set; }
        int OperatorpveTotalxp3DInfinite { get; set; }
        int OperatorpveTotalxp3FInfinite { get; set; }
        int OperatorpveTotalxp417Infinite { get; set; }
        int OperatorpveTotalxp41Infinite { get; set; }
        int OperatorpveTotalxp42Infinite { get; set; }
        int OperatorpveTotalxp43Infinite { get; set; }
        int OperatorpveTotalxp44Infinite { get; set; }
        int OperatorpveTotalxp4EInfinite { get; set; }
        int OperatorpveTotalxp51Infinite { get; set; }
        int OperatorpveTotalxp52Infinite { get; set; }
        int OperatorpveTotalxp53Infinite { get; set; }
        int OperatorpveTotalxp55Infinite { get; set; }
        int OperatorpveTwitchGadgetdestroybyshockdrone43Infinite { get; set; }
        int OperatorpvpAmaruDistancereeled216Infinite { get; set; }
        int OperatorpvpAshBonfirekill32Infinite { get; set; }
        int OperatorpvpAshBonfirewallbreached32Infinite { get; set; }
        int OperatorpvpAttackerdroneDiminishedrealitymode3DInfinite { get; set; }
        int OperatorpvpBarrageKillswithturret2FInfinite { get; set; }
        int OperatorpvpBlackbeardGunshieldblockdamage27Infinite { get; set; }
        int OperatorpvpBlackMirrorGadgetDeployed3AInfinite { get; set; }
        int OperatorpvpBlitzFlashedenemy25Infinite { get; set; }
        int OperatorpvpBlitzFlashfollowupkills25Infinite { get; set; }
        int OperatorpvpBlitzFlashshieldassist25Infinite { get; set; }
        int OperatorpvpBuckKill26Infinite { get; set; }
        int OperatorpvpCaltropEnemyAffected3BInfinite { get; set; }
        int OperatorpvpCapitaoLethaldartkills28Infinite { get; set; }
        int OperatorpvpCastleKevlarbarricadedeployed22Infinite { get; set; }
        int OperatorpvpCaveiraInterrogations38Infinite { get; set; }
        int OperatorpvpCazadorAssistKill2AInfinite { get; set; }
        int OperatorpvpConcussiongrenadeDetonate3CInfinite { get; set; }
        int OperatorpvpConcussionmineDetonate2CInfinite { get; set; }
        int OperatorpvpDazzlerGadgetDetonate2BInfinite { get; set; }
        int OperatorpvpDbno11BInfinite { get; set; }
        int OperatorpvpDbno12Infinite { get; set; }
        int OperatorpvpDbno13Infinite { get; set; }
        int OperatorpvpDbno15Infinite { get; set; }
        int OperatorpvpDbno210Infinite { get; set; }
        int OperatorpvpDbno212Infinite { get; set; }
        int OperatorpvpDbno213Infinite { get; set; }
        int OperatorpvpDbno214Infinite { get; set; }
        int OperatorpvpDbno215Infinite { get; set; }
        int OperatorpvpDbno216Infinite { get; set; }
        int OperatorpvpDbno218Infinite { get; set; }
        int OperatorpvpDbno219Infinite { get; set; }
        int OperatorpvpDbno21AInfinite { get; set; }
        int OperatorpvpDbno21Infinite { get; set; }
        int OperatorpvpDbno22Infinite { get; set; }
        int OperatorpvpDbno23Infinite { get; set; }
        int OperatorpvpDbno24Infinite { get; set; }
        int OperatorpvpDbno25Infinite { get; set; }
        int OperatorpvpDbno26Infinite { get; set; }
        int OperatorpvpDbno27Infinite { get; set; }
        int OperatorpvpDbno28Infinite { get; set; }
        int OperatorpvpDbno29Infinite { get; set; }
        int OperatorpvpDbno2AInfinite { get; set; }
        int OperatorpvpDbno2BInfinite { get; set; }
        int OperatorpvpDbno2CInfinite { get; set; }
        int OperatorpvpDbno2FInfinite { get; set; }
        int OperatorpvpDbno311Infinite { get; set; }
        int OperatorpvpDbno312Infinite { get; set; }
        int OperatorpvpDbno317Infinite { get; set; }
        int OperatorpvpDbno31AInfinite { get; set; }
        int OperatorpvpDbno31Infinite { get; set; }
        int OperatorpvpDbno32Infinite { get; set; }
        int OperatorpvpDbno33Infinite { get; set; }
        int OperatorpvpDbno34Infinite { get; set; }
        int OperatorpvpDbno35Infinite { get; set; }
        int OperatorpvpDbno36Infinite { get; set; }
        int OperatorpvpDbno37Infinite { get; set; }
        int OperatorpvpDbno38Infinite { get; set; }
        int OperatorpvpDbno3AInfinite { get; set; }
        int OperatorpvpDbno3BInfinite { get; set; }
        int OperatorpvpDbno3CInfinite { get; set; }
        int OperatorpvpDbno3DInfinite { get; set; }
        int OperatorpvpDbno3EInfinite { get; set; }
        int OperatorpvpDbno3FInfinite { get; set; }
        int OperatorpvpDbno416Infinite { get; set; }
        int OperatorpvpDbno417Infinite { get; set; }
        int OperatorpvpDbno41Infinite { get; set; }
        int OperatorpvpDbno42Infinite { get; set; }
        int OperatorpvpDbno43Infinite { get; set; }
        int OperatorpvpDbno44Infinite { get; set; }
        int OperatorpvpDbno45Infinite { get; set; }
        int OperatorpvpDbno4EInfinite { get; set; }
        int OperatorpvpDbno516Infinite { get; set; }
        int OperatorpvpDbno51Infinite { get; set; }
        int OperatorpvpDbno52Infinite { get; set; }
        int OperatorpvpDbno53Infinite { get; set; }
        int OperatorpvpDbno54Infinite { get; set; }
        int OperatorpvpDbno55Infinite { get; set; }
        int OperatorpvpDeath11BInfinite { get; set; }
        int OperatorpvpDeath11Infinite { get; set; }
        int OperatorpvpDeath12Infinite { get; set; }
        int OperatorpvpDeath13Infinite { get; set; }
        int OperatorpvpDeath14Infinite { get; set; }
        int OperatorpvpDeath15Infinite { get; set; }
        int OperatorpvpDeath210Infinite { get; set; }
        int OperatorpvpDeath211Infinite { get; set; }
        int OperatorpvpDeath212Infinite { get; set; }
        int OperatorpvpDeath213Infinite { get; set; }
        int OperatorpvpDeath214Infinite { get; set; }
        int OperatorpvpDeath215Infinite { get; set; }
        int OperatorpvpDeath216Infinite { get; set; }
        int OperatorpvpDeath218Infinite { get; set; }
        int OperatorpvpDeath219Infinite { get; set; }
        int OperatorpvpDeath21AInfinite { get; set; }
        int OperatorpvpDeath21Infinite { get; set; }
        int OperatorpvpDeath22Infinite { get; set; }
        int OperatorpvpDeath23Infinite { get; set; }
        int OperatorpvpDeath24Infinite { get; set; }
        int OperatorpvpDeath25Infinite { get; set; }
        int OperatorpvpDeath26Infinite { get; set; }
        int OperatorpvpDeath27Infinite { get; set; }
        int OperatorpvpDeath28Infinite { get; set; }
        int OperatorpvpDeath29Infinite { get; set; }
        int OperatorpvpDeath2AInfinite { get; set; }
        int OperatorpvpDeath2BInfinite { get; set; }
        int OperatorpvpDeath2CInfinite { get; set; }
        int OperatorpvpDeath2DInfinite { get; set; }
        int OperatorpvpDeath2FInfinite { get; set; }
        int OperatorpvpDeath310Infinite { get; set; }
        int OperatorpvpDeath311Infinite { get; set; }
        int OperatorpvpDeath312Infinite { get; set; }
        int OperatorpvpDeath316Infinite { get; set; }
        int OperatorpvpDeath317Infinite { get; set; }
        int OperatorpvpDeath31AInfinite { get; set; }
        int OperatorpvpDeath31Infinite { get; set; }
        int OperatorpvpDeath32Infinite { get; set; }
        int OperatorpvpDeath33Infinite { get; set; }
        int OperatorpvpDeath34Infinite { get; set; }
        int OperatorpvpDeath35Infinite { get; set; }
        int OperatorpvpDeath36Infinite { get; set; }
        int OperatorpvpDeath37Infinite { get; set; }
        int OperatorpvpDeath38Infinite { get; set; }
        int OperatorpvpDeath39Infinite { get; set; }
        int OperatorpvpDeath3AInfinite { get; set; }
        int OperatorpvpDeath3BInfinite { get; set; }
        int OperatorpvpDeath3CInfinite { get; set; }
        int OperatorpvpDeath3DInfinite { get; set; }
        int OperatorpvpDeath3EInfinite { get; set; }
        int OperatorpvpDeath3FInfinite { get; set; }
        int OperatorpvpDeath416Infinite { get; set; }
        int OperatorpvpDeath417Infinite { get; set; }
        int OperatorpvpDeath41AInfinite { get; set; }
        int OperatorpvpDeath41Infinite { get; set; }
        int OperatorpvpDeath42Infinite { get; set; }
        int OperatorpvpDeath43Infinite { get; set; }
        int OperatorpvpDeath44Infinite { get; set; }
        int OperatorpvpDeath45Infinite { get; set; }
        int OperatorpvpDeath4EInfinite { get; set; }
        int OperatorpvpDeath516Infinite { get; set; }
        int OperatorpvpDeath51Infinite { get; set; }
        int OperatorpvpDeath52Infinite { get; set; }
        int OperatorpvpDeath53Infinite { get; set; }
        int OperatorpvpDeath54Infinite { get; set; }
        int OperatorpvpDeath55Infinite { get; set; }
        int OperatorpvpDeath616Infinite { get; set; }
        int OperatorpvpDeath61AInfinite { get; set; }
        int OperatorpvpDeath716Infinite { get; set; }
        int OperatorpvpDeath816Infinite { get; set; }
        int OperatorpvpDeceiverRevealedattackers3FInfinite { get; set; }
        int OperatorpvpDocHostagerevive23Infinite { get; set; }
        int OperatorpvpDocSelfrevive23Infinite { get; set; }
        int OperatorpvpDocTeammaterevive23Infinite { get; set; }
        int OperatorpvpEchoEnemySonicburstAffected39Infinite { get; set; }
        int OperatorpvpFrostDbno36Infinite { get; set; }
        int OperatorpvpFuzeClusterchargekill34Infinite { get; set; }
        int OperatorpvpGlazSniperkill24Infinite { get; set; }
        int OperatorpvpGlazSniperpenetrationkill24Infinite { get; set; }
        int OperatorpvpGoyoVolcandetonate215Infinite { get; set; }
        int OperatorpvpGridlockTraxdeployed312Infinite { get; set; }
        int OperatorpvpHeadshot11BInfinite { get; set; }
        int OperatorpvpHeadshot12Infinite { get; set; }
        int OperatorpvpHeadshot15Infinite { get; set; }
        int OperatorpvpHeadshot210Infinite { get; set; }
        int OperatorpvpHeadshot211Infinite { get; set; }
        int OperatorpvpHeadshot212Infinite { get; set; }
        int OperatorpvpHeadshot213Infinite { get; set; }
        int OperatorpvpHeadshot214Infinite { get; set; }
        int OperatorpvpHeadshot215Infinite { get; set; }
        int OperatorpvpHeadshot216Infinite { get; set; }
        int OperatorpvpHeadshot218Infinite { get; set; }
        int OperatorpvpHeadshot219Infinite { get; set; }
        int OperatorpvpHeadshot21AInfinite { get; set; }
        int OperatorpvpHeadshot21Infinite { get; set; }
        int OperatorpvpHeadshot22Infinite { get; set; }
        int OperatorpvpHeadshot23Infinite { get; set; }
        int OperatorpvpHeadshot24Infinite { get; set; }
        int OperatorpvpHeadshot25Infinite { get; set; }
        int OperatorpvpHeadshot26Infinite { get; set; }
        int OperatorpvpHeadshot27Infinite { get; set; }
        int OperatorpvpHeadshot28Infinite { get; set; }
        int OperatorpvpHeadshot29Infinite { get; set; }
        int OperatorpvpHeadshot2AInfinite { get; set; }
        int OperatorpvpHeadshot2BInfinite { get; set; }
        int OperatorpvpHeadshot2CInfinite { get; set; }
        int OperatorpvpHeadshot2FInfinite { get; set; }
        int OperatorpvpHeadshot311Infinite { get; set; }
        int OperatorpvpHeadshot312Infinite { get; set; }
        int OperatorpvpHeadshot317Infinite { get; set; }
        int OperatorpvpHeadshot31Infinite { get; set; }
        int OperatorpvpHeadshot32Infinite { get; set; }
        int OperatorpvpHeadshot33Infinite { get; set; }
        int OperatorpvpHeadshot34Infinite { get; set; }
        int OperatorpvpHeadshot35Infinite { get; set; }
        int OperatorpvpHeadshot36Infinite { get; set; }
        int OperatorpvpHeadshot37Infinite { get; set; }
        int OperatorpvpHeadshot38Infinite { get; set; }
        int OperatorpvpHeadshot39Infinite { get; set; }
        int OperatorpvpHeadshot3AInfinite { get; set; }
        int OperatorpvpHeadshot3BInfinite { get; set; }
        int OperatorpvpHeadshot3CInfinite { get; set; }
        int OperatorpvpHeadshot3DInfinite { get; set; }
        int OperatorpvpHeadshot3EInfinite { get; set; }
        int OperatorpvpHeadshot3FInfinite { get; set; }
        int OperatorpvpHeadshot417Infinite { get; set; }
        int OperatorpvpHeadshot41Infinite { get; set; }
        int OperatorpvpHeadshot42Infinite { get; set; }
        int OperatorpvpHeadshot43Infinite { get; set; }
        int OperatorpvpHeadshot44Infinite { get; set; }
        int OperatorpvpHeadshot45Infinite { get; set; }
        int OperatorpvpHeadshot4EInfinite { get; set; }
        int OperatorpvpHeadshot51Infinite { get; set; }
        int OperatorpvpHeadshot52Infinite { get; set; }
        int OperatorpvpHeadshot53Infinite { get; set; }
        int OperatorpvpHeadshot54Infinite { get; set; }
        int OperatorpvpHeadshot55Infinite { get; set; }
        int OperatorpvpHibanaDetonateProjectile29Infinite { get; set; }
        int OperatorpvpIanaKillsafterreplicator219Infinite { get; set; }
        int OperatorpvpIqGadgetspotbyef35Infinite { get; set; }
        int OperatorpvpJagerGadgetdestroybycatcher45Infinite { get; set; }
        int OperatorpvpKaidElectroclawelectrify311Infinite { get; set; }
        int OperatorpvpKapkanBoobytrapdeployed44Infinite { get; set; }
        int OperatorpvpKapkanBoobytrapkill44Infinite { get; set; }
        int OperatorpvpKills116Infinite { get; set; }
        int OperatorpvpKills11BInfinite { get; set; }
        int OperatorpvpKills12Infinite { get; set; }
        int OperatorpvpKills13Infinite { get; set; }
        int OperatorpvpKills14Infinite { get; set; }
        int OperatorpvpKills15Infinite { get; set; }
        int OperatorpvpKills210Infinite { get; set; }
        int OperatorpvpKills211Infinite { get; set; }
        int OperatorpvpKills212Infinite { get; set; }
        int OperatorpvpKills213Infinite { get; set; }
        int OperatorpvpKills214Infinite { get; set; }
        int OperatorpvpKills215Infinite { get; set; }
        int OperatorpvpKills216Infinite { get; set; }
        int OperatorpvpKills218Infinite { get; set; }
        int OperatorpvpKills219Infinite { get; set; }
        int OperatorpvpKills21AInfinite { get; set; }
        int OperatorpvpKills21Infinite { get; set; }
        int OperatorpvpKills22Infinite { get; set; }
        int OperatorpvpKills23Infinite { get; set; }
        int OperatorpvpKills24Infinite { get; set; }
        int OperatorpvpKills25Infinite { get; set; }
        int OperatorpvpKills26Infinite { get; set; }
        int OperatorpvpKills27Infinite { get; set; }
        int OperatorpvpKills28Infinite { get; set; }
        int OperatorpvpKills29Infinite { get; set; }
        int OperatorpvpKills2AInfinite { get; set; }
        int OperatorpvpKills2BInfinite { get; set; }
        int OperatorpvpKills2CInfinite { get; set; }
        int OperatorpvpKills2DInfinite { get; set; }
        int OperatorpvpKills2FInfinite { get; set; }
        int OperatorpvpKills310Infinite { get; set; }
        int OperatorpvpKills311Infinite { get; set; }
        int OperatorpvpKills312Infinite { get; set; }
        int OperatorpvpKills316Infinite { get; set; }
        int OperatorpvpKills317Infinite { get; set; }
        int OperatorpvpKills31AInfinite { get; set; }
        int OperatorpvpKills31Infinite { get; set; }
        int OperatorpvpKills32Infinite { get; set; }
        int OperatorpvpKills33Infinite { get; set; }
        int OperatorpvpKills34Infinite { get; set; }
        int OperatorpvpKills35Infinite { get; set; }
        int OperatorpvpKills36Infinite { get; set; }
        int OperatorpvpKills37Infinite { get; set; }
        int OperatorpvpKills38Infinite { get; set; }
        int OperatorpvpKills39Infinite { get; set; }
        int OperatorpvpKills3AInfinite { get; set; }
        int OperatorpvpKills3BInfinite { get; set; }
        int OperatorpvpKills3CInfinite { get; set; }
        int OperatorpvpKills3DInfinite { get; set; }
        int OperatorpvpKills3EInfinite { get; set; }
        int OperatorpvpKills3FInfinite { get; set; }
        int OperatorpvpKills417Infinite { get; set; }
        int OperatorpvpKills41Infinite { get; set; }
        int OperatorpvpKills42Infinite { get; set; }
        int OperatorpvpKills43Infinite { get; set; }
        int OperatorpvpKills44Infinite { get; set; }
        int OperatorpvpKills45Infinite { get; set; }
        int OperatorpvpKills4EInfinite { get; set; }
        int OperatorpvpKills516Infinite { get; set; }
        int OperatorpvpKills51Infinite { get; set; }
        int OperatorpvpKills52Infinite { get; set; }
        int OperatorpvpKills53Infinite { get; set; }
        int OperatorpvpKills54Infinite { get; set; }
        int OperatorpvpKills55Infinite { get; set; }
        int OperatorpvpMaverickWallbreached210Infinite { get; set; }
        int OperatorpvpMeleekills11BInfinite { get; set; }
        int OperatorpvpMeleekills12Infinite { get; set; }
        int OperatorpvpMeleekills15Infinite { get; set; }
        int OperatorpvpMeleekills210Infinite { get; set; }
        int OperatorpvpMeleekills213Infinite { get; set; }
        int OperatorpvpMeleekills219Infinite { get; set; }
        int OperatorpvpMeleekills21AInfinite { get; set; }
        int OperatorpvpMeleekills22Infinite { get; set; }
        int OperatorpvpMeleekills23Infinite { get; set; }
        int OperatorpvpMeleekills25Infinite { get; set; }
        int OperatorpvpMeleekills26Infinite { get; set; }
        int OperatorpvpMeleekills28Infinite { get; set; }
        int OperatorpvpMeleekills29Infinite { get; set; }
        int OperatorpvpMeleekills2AInfinite { get; set; }
        int OperatorpvpMeleekills2BInfinite { get; set; }
        int OperatorpvpMeleekills2CInfinite { get; set; }
        int OperatorpvpMeleekills2FInfinite { get; set; }
        int OperatorpvpMeleekills32Infinite { get; set; }
        int OperatorpvpMeleekills33Infinite { get; set; }
        int OperatorpvpMeleekills34Infinite { get; set; }
        int OperatorpvpMeleekills35Infinite { get; set; }
        int OperatorpvpMeleekills36Infinite { get; set; }
        int OperatorpvpMeleekills37Infinite { get; set; }
        int OperatorpvpMeleekills3CInfinite { get; set; }
        int OperatorpvpMeleekills3DInfinite { get; set; }
        int OperatorpvpMeleekills3FInfinite { get; set; }
        int OperatorpvpMeleekills42Infinite { get; set; }
        int OperatorpvpMeleekills43Infinite { get; set; }
        int OperatorpvpMeleekills44Infinite { get; set; }
        int OperatorpvpMeleekills45Infinite { get; set; }
        int OperatorpvpMeleekills4EInfinite { get; set; }
        int OperatorpvpMeleekills51Infinite { get; set; }
        int OperatorpvpMeleekills52Infinite { get; set; }
        int OperatorpvpMeleekills53Infinite { get; set; }
        int OperatorpvpMeleekills55Infinite { get; set; }
        int OperatorpvpMelusiSloweddown21AInfinite { get; set; }
        int OperatorpvpMontagneShieldblockdamage53Infinite { get; set; }
        int OperatorpvpMozzieDroneshacked212Infinite { get; set; }
        int OperatorpvpMuteGadgetjammed31Infinite { get; set; }
        int OperatorpvpMuteJammerdeployed31Infinite { get; set; }
        int OperatorpvpNokkObservationtooldeceived213Infinite { get; set; }
        int OperatorpvpNomadAirjabdetonate211Infinite { get; set; }
        int OperatorpvpPulseHeartbeatassist42Infinite { get; set; }
        int OperatorpvpPulseHeartbeatspot42Infinite { get; set; }
        int OperatorpvpRookArmorboxdeployed33Infinite { get; set; }
        int OperatorpvpRookArmortakenourself33Infinite { get; set; }
        int OperatorpvpRookArmortakenteammate33Infinite { get; set; }
        int OperatorpvpRoundlost11BInfinite { get; set; }
        int OperatorpvpRoundlost11Infinite { get; set; }
        int OperatorpvpRoundlost12Infinite { get; set; }
        int OperatorpvpRoundlost13Infinite { get; set; }
        int OperatorpvpRoundlost14Infinite { get; set; }
        int OperatorpvpRoundlost15Infinite { get; set; }
        int OperatorpvpRoundlost210Infinite { get; set; }
        int OperatorpvpRoundlost211Infinite { get; set; }
        int OperatorpvpRoundlost212Infinite { get; set; }
        int OperatorpvpRoundlost213Infinite { get; set; }
        int OperatorpvpRoundlost214Infinite { get; set; }
        int OperatorpvpRoundlost215Infinite { get; set; }
        int OperatorpvpRoundlost216Infinite { get; set; }
        int OperatorpvpRoundlost218Infinite { get; set; }
        int OperatorpvpRoundlost219Infinite { get; set; }
        int OperatorpvpRoundlost21AInfinite { get; set; }
        int OperatorpvpRoundlost21Infinite { get; set; }
        int OperatorpvpRoundlost22Infinite { get; set; }
        int OperatorpvpRoundlost23Infinite { get; set; }
        int OperatorpvpRoundlost24Infinite { get; set; }
        int OperatorpvpRoundlost25Infinite { get; set; }
        int OperatorpvpRoundlost26Infinite { get; set; }
        int OperatorpvpRoundlost27Infinite { get; set; }
        int OperatorpvpRoundlost28Infinite { get; set; }
        int OperatorpvpRoundlost29Infinite { get; set; }
        int OperatorpvpRoundlost2AInfinite { get; set; }
        int OperatorpvpRoundlost2BInfinite { get; set; }
        int OperatorpvpRoundlost2CInfinite { get; set; }
        int OperatorpvpRoundlost2FInfinite { get; set; }
        int OperatorpvpRoundlost311Infinite { get; set; }
        int OperatorpvpRoundlost312Infinite { get; set; }
        int OperatorpvpRoundlost316Infinite { get; set; }
        int OperatorpvpRoundlost317Infinite { get; set; }
        int OperatorpvpRoundlost31AInfinite { get; set; }
        int OperatorpvpRoundlost31Infinite { get; set; }
        int OperatorpvpRoundlost32Infinite { get; set; }
        int OperatorpvpRoundlost33Infinite { get; set; }
        int OperatorpvpRoundlost34Infinite { get; set; }
        int OperatorpvpRoundlost35Infinite { get; set; }
        int OperatorpvpRoundlost36Infinite { get; set; }
        int OperatorpvpRoundlost37Infinite { get; set; }
        int OperatorpvpRoundlost38Infinite { get; set; }
        int OperatorpvpRoundlost39Infinite { get; set; }
        int OperatorpvpRoundlost3AInfinite { get; set; }
        int OperatorpvpRoundlost3BInfinite { get; set; }
        int OperatorpvpRoundlost3CInfinite { get; set; }
        int OperatorpvpRoundlost3DInfinite { get; set; }
        int OperatorpvpRoundlost3EInfinite { get; set; }
        int OperatorpvpRoundlost3FInfinite { get; set; }
        int OperatorpvpRoundlost416Infinite { get; set; }
        int OperatorpvpRoundlost417Infinite { get; set; }
        int OperatorpvpRoundlost41AInfinite { get; set; }
        int OperatorpvpRoundlost41Infinite { get; set; }
        int OperatorpvpRoundlost42Infinite { get; set; }
        int OperatorpvpRoundlost43Infinite { get; set; }
        int OperatorpvpRoundlost44Infinite { get; set; }
        int OperatorpvpRoundlost45Infinite { get; set; }
        int OperatorpvpRoundlost4EInfinite { get; set; }
        int OperatorpvpRoundlost516Infinite { get; set; }
        int OperatorpvpRoundlost51Infinite { get; set; }
        int OperatorpvpRoundlost52Infinite { get; set; }
        int OperatorpvpRoundlost53Infinite { get; set; }
        int OperatorpvpRoundlost54Infinite { get; set; }
        int OperatorpvpRoundlost55Infinite { get; set; }
        int OperatorpvpRoundlost616Infinite { get; set; }
        int OperatorpvpRoundlost61AInfinite { get; set; }
        int OperatorpvpRoundlost716Infinite { get; set; }
        int OperatorpvpRoundlost816Infinite { get; set; }
        int OperatorpvpRoundplayed116Infinite { get; set; }
        int OperatorpvpRoundplayed11BInfinite { get; set; }
        int OperatorpvpRoundplayed11Infinite { get; set; }
        int OperatorpvpRoundplayed12Infinite { get; set; }
        int OperatorpvpRoundplayed13Infinite { get; set; }
        int OperatorpvpRoundplayed14Infinite { get; set; }
        int OperatorpvpRoundplayed15Infinite { get; set; }
        int OperatorpvpRoundplayed210Infinite { get; set; }
        int OperatorpvpRoundplayed211Infinite { get; set; }
        int OperatorpvpRoundplayed212Infinite { get; set; }
        int OperatorpvpRoundplayed213Infinite { get; set; }
        int OperatorpvpRoundplayed214Infinite { get; set; }
        int OperatorpvpRoundplayed215Infinite { get; set; }
        int OperatorpvpRoundplayed216Infinite { get; set; }
        int OperatorpvpRoundplayed218Infinite { get; set; }
        int OperatorpvpRoundplayed219Infinite { get; set; }
        int OperatorpvpRoundplayed21AInfinite { get; set; }
        int OperatorpvpRoundplayed21Infinite { get; set; }
        int OperatorpvpRoundplayed22Infinite { get; set; }
        int OperatorpvpRoundplayed23Infinite { get; set; }
        int OperatorpvpRoundplayed24Infinite { get; set; }
        int OperatorpvpRoundplayed25Infinite { get; set; }
        int OperatorpvpRoundplayed26Infinite { get; set; }
        int OperatorpvpRoundplayed27Infinite { get; set; }
        int OperatorpvpRoundplayed28Infinite { get; set; }
        int OperatorpvpRoundplayed29Infinite { get; set; }
        int OperatorpvpRoundplayed2AInfinite { get; set; }
        int OperatorpvpRoundplayed2BInfinite { get; set; }
        int OperatorpvpRoundplayed2CInfinite { get; set; }
        int OperatorpvpRoundplayed2DInfinite { get; set; }
        int OperatorpvpRoundplayed2FInfinite { get; set; }
        int OperatorpvpRoundplayed310Infinite { get; set; }
        int OperatorpvpRoundplayed311Infinite { get; set; }
        int OperatorpvpRoundplayed312Infinite { get; set; }
        int OperatorpvpRoundplayed316Infinite { get; set; }
        int OperatorpvpRoundplayed317Infinite { get; set; }
        int OperatorpvpRoundplayed31AInfinite { get; set; }
        int OperatorpvpRoundplayed31Infinite { get; set; }
        int OperatorpvpRoundplayed32Infinite { get; set; }
        int OperatorpvpRoundplayed33Infinite { get; set; }
        int OperatorpvpRoundplayed34Infinite { get; set; }
        int OperatorpvpRoundplayed35Infinite { get; set; }
        int OperatorpvpRoundplayed36Infinite { get; set; }
        int OperatorpvpRoundplayed37Infinite { get; set; }
        int OperatorpvpRoundplayed38Infinite { get; set; }
        int OperatorpvpRoundplayed39Infinite { get; set; }
        int OperatorpvpRoundplayed3AInfinite { get; set; }
        int OperatorpvpRoundplayed3BInfinite { get; set; }
        int OperatorpvpRoundplayed3CInfinite { get; set; }
        int OperatorpvpRoundplayed3DInfinite { get; set; }
        int OperatorpvpRoundplayed3EInfinite { get; set; }
        int OperatorpvpRoundplayed3FInfinite { get; set; }
        int OperatorpvpRoundplayed416Infinite { get; set; }
        int OperatorpvpRoundplayed417Infinite { get; set; }
        int OperatorpvpRoundplayed41AInfinite { get; set; }
        int OperatorpvpRoundplayed41Infinite { get; set; }
        int OperatorpvpRoundplayed42Infinite { get; set; }
        int OperatorpvpRoundplayed43Infinite { get; set; }
        int OperatorpvpRoundplayed44Infinite { get; set; }
        int OperatorpvpRoundplayed45Infinite { get; set; }
        int OperatorpvpRoundplayed4EInfinite { get; set; }
        int OperatorpvpRoundplayed516Infinite { get; set; }
        int OperatorpvpRoundplayed51Infinite { get; set; }
        int OperatorpvpRoundplayed52Infinite { get; set; }
        int OperatorpvpRoundplayed53Infinite { get; set; }
        int OperatorpvpRoundplayed54Infinite { get; set; }
        int OperatorpvpRoundplayed55Infinite { get; set; }
        int OperatorpvpRoundplayed616Infinite { get; set; }
        int OperatorpvpRoundplayed61AInfinite { get; set; }
        int OperatorpvpRoundplayed716Infinite { get; set; }
        int OperatorpvpRoundplayed816Infinite { get; set; }
        int OperatorpvpRoundwon116Infinite { get; set; }
        int OperatorpvpRoundwon11BInfinite { get; set; }
        int OperatorpvpRoundwon12Infinite { get; set; }
        int OperatorpvpRoundwon13Infinite { get; set; }
        int OperatorpvpRoundwon14Infinite { get; set; }
        int OperatorpvpRoundwon15Infinite { get; set; }
        int OperatorpvpRoundwon210Infinite { get; set; }
        int OperatorpvpRoundwon211Infinite { get; set; }
        int OperatorpvpRoundwon212Infinite { get; set; }
        int OperatorpvpRoundwon213Infinite { get; set; }
        int OperatorpvpRoundwon214Infinite { get; set; }
        int OperatorpvpRoundwon215Infinite { get; set; }
        int OperatorpvpRoundwon216Infinite { get; set; }
        int OperatorpvpRoundwon218Infinite { get; set; }
        int OperatorpvpRoundwon219Infinite { get; set; }
        int OperatorpvpRoundwon21AInfinite { get; set; }
        int OperatorpvpRoundwon21Infinite { get; set; }
        int OperatorpvpRoundwon22Infinite { get; set; }
        int OperatorpvpRoundwon23Infinite { get; set; }
        int OperatorpvpRoundwon24Infinite { get; set; }
        int OperatorpvpRoundwon25Infinite { get; set; }
        int OperatorpvpRoundwon26Infinite { get; set; }
        int OperatorpvpRoundwon27Infinite { get; set; }
        int OperatorpvpRoundwon28Infinite { get; set; }
        int OperatorpvpRoundwon29Infinite { get; set; }
        int OperatorpvpRoundwon2AInfinite { get; set; }
        int OperatorpvpRoundwon2BInfinite { get; set; }
        int OperatorpvpRoundwon2CInfinite { get; set; }
        int OperatorpvpRoundwon2DInfinite { get; set; }
        int OperatorpvpRoundwon2FInfinite { get; set; }
        int OperatorpvpRoundwon310Infinite { get; set; }
        int OperatorpvpRoundwon311Infinite { get; set; }
        int OperatorpvpRoundwon312Infinite { get; set; }
        int OperatorpvpRoundwon316Infinite { get; set; }
        int OperatorpvpRoundwon317Infinite { get; set; }
        int OperatorpvpRoundwon31AInfinite { get; set; }
        int OperatorpvpRoundwon31Infinite { get; set; }
        int OperatorpvpRoundwon32Infinite { get; set; }
        int OperatorpvpRoundwon33Infinite { get; set; }
        int OperatorpvpRoundwon34Infinite { get; set; }
        int OperatorpvpRoundwon35Infinite { get; set; }
        int OperatorpvpRoundwon36Infinite { get; set; }
        int OperatorpvpRoundwon37Infinite { get; set; }
        int OperatorpvpRoundwon38Infinite { get; set; }
        int OperatorpvpRoundwon39Infinite { get; set; }
        int OperatorpvpRoundwon3AInfinite { get; set; }
        int OperatorpvpRoundwon3BInfinite { get; set; }
        int OperatorpvpRoundwon3CInfinite { get; set; }
        int OperatorpvpRoundwon3DInfinite { get; set; }
        int OperatorpvpRoundwon3FInfinite { get; set; }
        int OperatorpvpRoundwon416Infinite { get; set; }
        int OperatorpvpRoundwon417Infinite { get; set; }
        int OperatorpvpRoundwon41Infinite { get; set; }
        int OperatorpvpRoundwon42Infinite { get; set; }
        int OperatorpvpRoundwon43Infinite { get; set; }
        int OperatorpvpRoundwon44Infinite { get; set; }
        int OperatorpvpRoundwon45Infinite { get; set; }
        int OperatorpvpRoundwon4EInfinite { get; set; }
        int OperatorpvpRoundwon516Infinite { get; set; }
        int OperatorpvpRoundwon51Infinite { get; set; }
        int OperatorpvpRoundwon52Infinite { get; set; }
        int OperatorpvpRoundwon53Infinite { get; set; }
        int OperatorpvpRoundwon54Infinite { get; set; }
        int OperatorpvpRoundwon55Infinite { get; set; }
        int OperatorpvpRoundwon716Infinite { get; set; }
        int OperatorpvpRushAdrenalinerush4EInfinite { get; set; }
        int OperatorpvpSledgeHammerhole41Infinite { get; set; }
        int OperatorpvpSledgeHammerkill41Infinite { get; set; }
        int OperatorpvpSmokePoisongaskill21Infinite { get; set; }
        int OperatorpvpTachankaTurretdeployed54Infinite { get; set; }
        int OperatorpvpTachankaTurretkill54Infinite { get; set; }
        int OperatorpvpThatcherGadgetdestroywithemp51Infinite { get; set; }
        int OperatorpvpThermiteChargedeployed52Infinite { get; set; }
        int OperatorpvpThermiteChargekill52Infinite { get; set; }
        int OperatorpvpThermiteReinforcementbreached52Infinite { get; set; }
        int OperatorpvpTimeplayed116Infinite { get; set; }
        int OperatorpvpTimeplayed11BInfinite { get; set; }
        int OperatorpvpTimeplayed11Infinite { get; set; }
        int OperatorpvpTimeplayed12Infinite { get; set; }
        int OperatorpvpTimeplayed13Infinite { get; set; }
        int OperatorpvpTimeplayed14Infinite { get; set; }
        int OperatorpvpTimeplayed15Infinite { get; set; }
        int OperatorpvpTimeplayed210Infinite { get; set; }
        int OperatorpvpTimeplayed211Infinite { get; set; }
        int OperatorpvpTimeplayed212Infinite { get; set; }
        int OperatorpvpTimeplayed213Infinite { get; set; }
        int OperatorpvpTimeplayed214Infinite { get; set; }
        int OperatorpvpTimeplayed215Infinite { get; set; }
        int OperatorpvpTimeplayed216Infinite { get; set; }
        int OperatorpvpTimeplayed218Infinite { get; set; }
        int OperatorpvpTimeplayed219Infinite { get; set; }
        int OperatorpvpTimeplayed21AInfinite { get; set; }
        int OperatorpvpTimeplayed21Infinite { get; set; }
        int OperatorpvpTimeplayed22Infinite { get; set; }
        int OperatorpvpTimeplayed23Infinite { get; set; }
        int OperatorpvpTimeplayed24Infinite { get; set; }
        int OperatorpvpTimeplayed25Infinite { get; set; }
        int OperatorpvpTimeplayed26Infinite { get; set; }
        int OperatorpvpTimeplayed27Infinite { get; set; }
        int OperatorpvpTimeplayed28Infinite { get; set; }
        int OperatorpvpTimeplayed29Infinite { get; set; }
        int OperatorpvpTimeplayed2AInfinite { get; set; }
        int OperatorpvpTimeplayed2BInfinite { get; set; }
        int OperatorpvpTimeplayed2CInfinite { get; set; }
        int OperatorpvpTimeplayed2DInfinite { get; set; }
        int OperatorpvpTimeplayed2FInfinite { get; set; }
        int OperatorpvpTimeplayed310Infinite { get; set; }
        int OperatorpvpTimeplayed311Infinite { get; set; }
        int OperatorpvpTimeplayed312Infinite { get; set; }
        int OperatorpvpTimeplayed316Infinite { get; set; }
        int OperatorpvpTimeplayed317Infinite { get; set; }
        int OperatorpvpTimeplayed31AInfinite { get; set; }
        int OperatorpvpTimeplayed31Infinite { get; set; }
        int OperatorpvpTimeplayed32Infinite { get; set; }
        int OperatorpvpTimeplayed33Infinite { get; set; }
        int OperatorpvpTimeplayed34Infinite { get; set; }
        int OperatorpvpTimeplayed35Infinite { get; set; }
        int OperatorpvpTimeplayed36Infinite { get; set; }
        int OperatorpvpTimeplayed37Infinite { get; set; }
        int OperatorpvpTimeplayed38Infinite { get; set; }
        int OperatorpvpTimeplayed39Infinite { get; set; }
        int OperatorpvpTimeplayed3AInfinite { get; set; }
        int OperatorpvpTimeplayed3BInfinite { get; set; }
        int OperatorpvpTimeplayed3CInfinite { get; set; }
        int OperatorpvpTimeplayed3DInfinite { get; set; }
        int OperatorpvpTimeplayed3EInfinite { get; set; }
        int OperatorpvpTimeplayed3FInfinite { get; set; }
        int OperatorpvpTimeplayed416Infinite { get; set; }
        int OperatorpvpTimeplayed417Infinite { get; set; }
        int OperatorpvpTimeplayed41AInfinite { get; set; }
        int OperatorpvpTimeplayed41Infinite { get; set; }
        int OperatorpvpTimeplayed42Infinite { get; set; }
        int OperatorpvpTimeplayed43Infinite { get; set; }
        int OperatorpvpTimeplayed44Infinite { get; set; }
        int OperatorpvpTimeplayed45Infinite { get; set; }
        int OperatorpvpTimeplayed4EInfinite { get; set; }
        int OperatorpvpTimeplayed516Infinite { get; set; }
        int OperatorpvpTimeplayed51Infinite { get; set; }
        int OperatorpvpTimeplayed52Infinite { get; set; }
        int OperatorpvpTimeplayed53Infinite { get; set; }
        int OperatorpvpTimeplayed54Infinite { get; set; }
        int OperatorpvpTimeplayed55Infinite { get; set; }
        int OperatorpvpTimeplayed616Infinite { get; set; }
        int OperatorpvpTimeplayed61AInfinite { get; set; }
        int OperatorpvpTimeplayed716Infinite { get; set; }
        int OperatorpvpTimeplayed816Infinite { get; set; }
        int OperatorpvpTotalxp116Infinite { get; set; }
        int OperatorpvpTotalxp11BInfinite { get; set; }
        int OperatorpvpTotalxp11Infinite { get; set; }
        int OperatorpvpTotalxp12Infinite { get; set; }
        int OperatorpvpTotalxp13Infinite { get; set; }
        int OperatorpvpTotalxp14Infinite { get; set; }
        int OperatorpvpTotalxp15Infinite { get; set; }
        int OperatorpvpTotalxp210Infinite { get; set; }
        int OperatorpvpTotalxp211Infinite { get; set; }
        int OperatorpvpTotalxp212Infinite { get; set; }
        int OperatorpvpTotalxp213Infinite { get; set; }
        int OperatorpvpTotalxp214Infinite { get; set; }
        int OperatorpvpTotalxp215Infinite { get; set; }
        int OperatorpvpTotalxp216Infinite { get; set; }
        int OperatorpvpTotalxp218Infinite { get; set; }
        int OperatorpvpTotalxp219Infinite { get; set; }
        int OperatorpvpTotalxp21AInfinite { get; set; }
        int OperatorpvpTotalxp21Infinite { get; set; }
        int OperatorpvpTotalxp22Infinite { get; set; }
        int OperatorpvpTotalxp23Infinite { get; set; }
        int OperatorpvpTotalxp24Infinite { get; set; }
        int OperatorpvpTotalxp25Infinite { get; set; }
        int OperatorpvpTotalxp26Infinite { get; set; }
        int OperatorpvpTotalxp27Infinite { get; set; }
        int OperatorpvpTotalxp28Infinite { get; set; }
        int OperatorpvpTotalxp29Infinite { get; set; }
        int OperatorpvpTotalxp2AInfinite { get; set; }
        int OperatorpvpTotalxp2BInfinite { get; set; }
        int OperatorpvpTotalxp2CInfinite { get; set; }
        int OperatorpvpTotalxp2DInfinite { get; set; }
        int OperatorpvpTotalxp2FInfinite { get; set; }
        int OperatorpvpTotalxp310Infinite { get; set; }
        int OperatorpvpTotalxp311Infinite { get; set; }
        int OperatorpvpTotalxp312Infinite { get; set; }
        int OperatorpvpTotalxp316Infinite { get; set; }
        int OperatorpvpTotalxp317Infinite { get; set; }
        int OperatorpvpTotalxp31AInfinite { get; set; }
        int OperatorpvpTotalxp31Infinite { get; set; }
        int OperatorpvpTotalxp32Infinite { get; set; }
        int OperatorpvpTotalxp33Infinite { get; set; }
        int OperatorpvpTotalxp34Infinite { get; set; }
        int OperatorpvpTotalxp35Infinite { get; set; }
        int OperatorpvpTotalxp36Infinite { get; set; }
        int OperatorpvpTotalxp37Infinite { get; set; }
        int OperatorpvpTotalxp38Infinite { get; set; }
        int OperatorpvpTotalxp39Infinite { get; set; }
        int OperatorpvpTotalxp3AInfinite { get; set; }
        int OperatorpvpTotalxp3BInfinite { get; set; }
        int OperatorpvpTotalxp3CInfinite { get; set; }
        int OperatorpvpTotalxp3DInfinite { get; set; }
        int OperatorpvpTotalxp3EInfinite { get; set; }
        int OperatorpvpTotalxp3FInfinite { get; set; }
        int OperatorpvpTotalxp416Infinite { get; set; }
        int OperatorpvpTotalxp417Infinite { get; set; }
        int OperatorpvpTotalxp41AInfinite { get; set; }
        int OperatorpvpTotalxp41Infinite { get; set; }
        int OperatorpvpTotalxp42Infinite { get; set; }
        int OperatorpvpTotalxp43Infinite { get; set; }
        int OperatorpvpTotalxp44Infinite { get; set; }
        int OperatorpvpTotalxp45Infinite { get; set; }
        int OperatorpvpTotalxp4EInfinite { get; set; }
        int OperatorpvpTotalxp516Infinite { get; set; }
        int OperatorpvpTotalxp51Infinite { get; set; }
        int OperatorpvpTotalxp52Infinite { get; set; }
        int OperatorpvpTotalxp53Infinite { get; set; }
        int OperatorpvpTotalxp54Infinite { get; set; }
        int OperatorpvpTotalxp55Infinite { get; set; }
        int OperatorpvpTotalxp61AInfinite { get; set; }
        int OperatorpvpTotalxp716Infinite { get; set; }
        int OperatorpvpTotalxp816Infinite { get; set; }
        int OperatorpvpTwitchGadgetdestroybyshockdrone43Infinite { get; set; }
        int OperatorpvpValkyrieCamdeployed37Infinite { get; set; }
        int OperatorpvpWamaiGadgetdestroybymagnet317Infinite { get; set; }
        int OperatorpvpWardenKillswithglasses214Infinite { get; set; }
    }
}